taskkill /F /IM msedge.exe /T
taskkill /F /IM PhoneExperienceHost.exe /T
taskkill /F /IM CrossDeviceService.exe /T
taskkill /F /IM GameBar.exe /T
taskkill /F /IM GameBarFTServer.exe /T
taskkill /F /IM EdgeGameAssist.exe /T
taskkill /F /IM GameBarFTServer.exe /T
taskkill /F /IM Copilot.exe /T
taskkill /F /IM XboxPcAppFT.exe /T